.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel bzero
/* 2CF0 800020F0 28A1000C */  slti       $at, $a1, 0xC
/* 2CF4 800020F4 1420001D */  bnez       $at, .L8000216C
/* 2CF8 800020F8 00041823 */   negu      $v1, $a0
/* 2CFC 800020FC 30630003 */  andi       $v1, $v1, 0x3
/* 2D00 80002100 10600003 */  beqz       $v1, .L80002110
/* 2D04 80002104 00A32823 */   subu      $a1, $a1, $v1
/* 2D08 80002108 A8800000 */  swl        $zero, 0x0($a0)
/* 2D0C 8000210C 00832021 */  addu       $a0, $a0, $v1
.L80002110:
/* 2D10 80002110 2401FFE0 */  addiu      $at, $zero, -0x20
/* 2D14 80002114 00A13824 */  and        $a3, $a1, $at
/* 2D18 80002118 10E0000C */  beqz       $a3, .L8000214C
/* 2D1C 8000211C 00A72823 */   subu      $a1, $a1, $a3
/* 2D20 80002120 00E43821 */  addu       $a3, $a3, $a0
.L80002124:
/* 2D24 80002124 24840020 */  addiu      $a0, $a0, 0x20
/* 2D28 80002128 AC80FFE0 */  sw         $zero, -0x20($a0)
/* 2D2C 8000212C AC80FFE4 */  sw         $zero, -0x1C($a0)
/* 2D30 80002130 AC80FFE8 */  sw         $zero, -0x18($a0)
/* 2D34 80002134 AC80FFEC */  sw         $zero, -0x14($a0)
/* 2D38 80002138 AC80FFF0 */  sw         $zero, -0x10($a0)
/* 2D3C 8000213C AC80FFF4 */  sw         $zero, -0xC($a0)
/* 2D40 80002140 AC80FFF8 */  sw         $zero, -0x8($a0)
/* 2D44 80002144 1487FFF7 */  bne        $a0, $a3, .L80002124
/* 2D48 80002148 AC80FFFC */   sw        $zero, -0x4($a0)
.L8000214C:
/* 2D4C 8000214C 2401FFFC */  addiu      $at, $zero, -0x4
/* 2D50 80002150 00A13824 */  and        $a3, $a1, $at
/* 2D54 80002154 10E00005 */  beqz       $a3, .L8000216C
/* 2D58 80002158 00A72823 */   subu      $a1, $a1, $a3
/* 2D5C 8000215C 00E43821 */  addu       $a3, $a3, $a0
.L80002160:
/* 2D60 80002160 24840004 */  addiu      $a0, $a0, 0x4
/* 2D64 80002164 1487FFFE */  bne        $a0, $a3, .L80002160
/* 2D68 80002168 AC80FFFC */   sw        $zero, -0x4($a0)
.L8000216C:
/* 2D6C 8000216C 18A00005 */  blez       $a1, .L80002184
/* 2D70 80002170 00000000 */   nop
/* 2D74 80002174 00A42821 */  addu       $a1, $a1, $a0
.L80002178:
/* 2D78 80002178 24840001 */  addiu      $a0, $a0, 0x1
/* 2D7C 8000217C 1485FFFE */  bne        $a0, $a1, .L80002178
/* 2D80 80002180 A080FFFF */   sb        $zero, -0x1($a0)
.L80002184:
/* 2D84 80002184 03E00008 */  jr         $ra
/* 2D88 80002188 00000000 */   nop
/* 2D8C 8000218C 00000000 */  nop
endlabel bzero
.size bzero, . - bzero
