.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel ___osGetSR
/* F36810 8025AFE0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
/* F36814 8025AFE4 03E00008 */  jr         $ra
/* F36818 8025AFE8 00000000 */   nop
/* F3681C 8025AFEC 00000000 */  nop
endlabel ___osGetSR
.size ___osGetSR, . - ___osGetSR
