.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osGetSR
/* 2DA0 800021A0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
/* 2DA4 800021A4 03E00008 */  jr         $ra
/* 2DA8 800021A8 00000000 */   nop
/* 2DAC 800021AC 00000000 */  nop
endlabel __osGetSR
.size __osGetSR, . - __osGetSR
