.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osInvalICache
/* 37F0 80002BF0 18A00011 */  blez       $a1, .L80002C38
/* 37F4 80002BF4 00000000 */   nop
/* 37F8 80002BF8 240B4000 */  addiu      $t3, $zero, 0x4000
/* 37FC 80002BFC 00AB082B */  sltu       $at, $a1, $t3
/* 3800 80002C00 1020000F */  beqz       $at, .L80002C40
/* 3804 80002C04 00000000 */   nop
/* 3808 80002C08 00804025 */  or         $t0, $a0, $zero
/* 380C 80002C0C 00854821 */  addu       $t1, $a0, $a1
/* 3810 80002C10 0109082B */  sltu       $at, $t0, $t1
/* 3814 80002C14 10200008 */  beqz       $at, .L80002C38
/* 3818 80002C18 00000000 */   nop
/* 381C 80002C1C 310A001F */  andi       $t2, $t0, 0x1F
/* 3820 80002C20 2529FFE0 */  addiu      $t1, $t1, -0x20
/* 3824 80002C24 010A4023 */  subu       $t0, $t0, $t2
.L80002C28:
/* 3828 80002C28 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
/* 382C 80002C2C 0109082B */  sltu       $at, $t0, $t1
/* 3830 80002C30 1420FFFD */  bnez       $at, .L80002C28
/* 3834 80002C34 25080020 */   addiu     $t0, $t0, 0x20
.L80002C38:
/* 3838 80002C38 03E00008 */  jr         $ra
/* 383C 80002C3C 00000000 */   nop
.L80002C40:
/* 3840 80002C40 3C088000 */  lui        $t0, 0x8000
/* 3844 80002C44 010B4821 */  addu       $t1, $t0, $t3
/* 3848 80002C48 2529FFE0 */  addiu      $t1, $t1, -0x20
.L80002C4C:
/* 384C 80002C4C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
/* 3850 80002C50 0109082B */  sltu       $at, $t0, $t1
/* 3854 80002C54 1420FFFD */  bnez       $at, .L80002C4C
/* 3858 80002C58 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
/* 385C 80002C5C 03E00008 */  jr         $ra
/* 3860 80002C60 00000000 */   nop
/* 3864 80002C64 00000000 */  nop
/* 3868 80002C68 00000000 */  nop
/* 386C 80002C6C 00000000 */  nop
endlabel osInvalICache
.size osInvalICache, . - osInvalICache
