.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osMapTLBRdb
/* 3870 80002C70 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* 3874 80002C74 2409001F */  addiu      $t1, $zero, 0x1F
/* 3878 80002C78 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
/* 387C 80002C7C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
/* 3880 80002C80 240A0017 */  addiu      $t2, $zero, 0x17
/* 3884 80002C84 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
/* 3888 80002C88 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* 388C 80002C8C 3C098000 */  lui        $t1, (0x80000000 >> 16)
/* 3890 80002C90 00095982 */  srl        $t3, $t1, 6
/* 3894 80002C94 016A5825 */  or         $t3, $t3, $t2
/* 3898 80002C98 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
/* 389C 80002C9C 24090001 */  addiu      $t1, $zero, 0x1
/* 38A0 80002CA0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
/* 38A4 80002CA4 00000000 */  nop
/* 38A8 80002CA8 42000002 */  tlbwi /* handwritten instruction */
/* 38AC 80002CAC 00000000 */  nop
/* 38B0 80002CB0 00000000 */  nop
/* 38B4 80002CB4 00000000 */  nop
/* 38B8 80002CB8 00000000 */  nop
/* 38BC 80002CBC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* 38C0 80002CC0 03E00008 */  jr         $ra
/* 38C4 80002CC4 00000000 */   nop
/* 38C8 80002CC8 00000000 */  nop
/* 38CC 80002CCC 00000000 */  nop
endlabel osMapTLBRdb
.size osMapTLBRdb, . - osMapTLBRdb
