.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osProbeTLB
/* 47D0 80003BD0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* 47D4 80003BD4 310900FF */  andi       $t1, $t0, 0xFF
/* 47D8 80003BD8 2401E000 */  addiu      $at, $zero, -0x2000
/* 47DC 80003BDC 00815024 */  and        $t2, $a0, $at
/* 47E0 80003BE0 012A4825 */  or         $t1, $t1, $t2
/* 47E4 80003BE4 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* 47E8 80003BE8 00000000 */  nop
/* 47EC 80003BEC 00000000 */  nop
/* 47F0 80003BF0 00000000 */  nop
/* 47F4 80003BF4 42000008 */  tlbp /* handwritten instruction */
/* 47F8 80003BF8 00000000 */  nop
/* 47FC 80003BFC 00000000 */  nop
/* 4800 80003C00 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
/* 4804 80003C04 3C018000 */  lui        $at, (0x80000000 >> 16)
/* 4808 80003C08 01615824 */  and        $t3, $t3, $at
/* 480C 80003C0C 1560001A */  bnez       $t3, .L80003C78
/* 4810 80003C10 00000000 */   nop
/* 4814 80003C14 42000001 */  tlbr /* handwritten instruction */
/* 4818 80003C18 00000000 */  nop
/* 481C 80003C1C 00000000 */  nop
/* 4820 80003C20 00000000 */  nop
/* 4824 80003C24 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
/* 4828 80003C28 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
/* 482C 80003C2C 000B5842 */  srl        $t3, $t3, 1
/* 4830 80003C30 01646024 */  and        $t4, $t3, $a0
/* 4834 80003C34 15800004 */  bnez       $t4, .L80003C48
/* 4838 80003C38 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
/* 483C 80003C3C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
/* 4840 80003C40 10000002 */  b          .L80003C4C
/* 4844 80003C44 00000000 */   nop
.L80003C48:
/* 4848 80003C48 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
.L80003C4C:
/* 484C 80003C4C 304D0002 */  andi       $t5, $v0, 0x2
/* 4850 80003C50 11A00009 */  beqz       $t5, .L80003C78
/* 4854 80003C54 00000000 */   nop
/* 4858 80003C58 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
/* 485C 80003C5C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
/* 4860 80003C60 00411024 */  and        $v0, $v0, $at
/* 4864 80003C64 00021180 */  sll        $v0, $v0, 6
/* 4868 80003C68 008B6824 */  and        $t5, $a0, $t3
/* 486C 80003C6C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
/* 4870 80003C70 10000002 */  b          .L80003C7C
/* 4874 80003C74 00000000 */   nop
.L80003C78:
/* 4878 80003C78 2402FFFF */  addiu      $v0, $zero, -0x1
.L80003C7C:
/* 487C 80003C7C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* 4880 80003C80 03E00008 */  jr         $ra
/* 4884 80003C84 00000000 */   nop
/* 4888 80003C88 00000000 */  nop
/* 488C 80003C8C 00000000 */  nop
endlabel __osProbeTLB
.size __osProbeTLB, . - __osProbeTLB
