.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel __osSetFpcCsr
/* 2DB0 800021B0 4442F800 */  cfc1       $v0, $31
/* 2DB4 800021B4 44C4F800 */  ctc1       $a0, $31
/* 2DB8 800021B8 03E00008 */  jr         $ra
/* 2DBC 800021BC 00000000 */   nop
endlabel __osSetFpcCsr
.size __osSetFpcCsr, . - __osSetFpcCsr
