.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osSetSR
/* 2D90 80002190 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
/* 2D94 80002194 00000000 */  nop
/* 2D98 80002198 03E00008 */  jr         $ra
/* 2D9C 8000219C 00000000 */   nop
endlabel __osSetSR
.size __osSetSR, . - __osSetSR
