.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osWritebackDCache
/* 3770 80002B70 18A00011 */  blez       $a1, .L80002BB8
/* 3774 80002B74 00000000 */   nop
/* 3778 80002B78 240B2000 */  addiu      $t3, $zero, 0x2000
/* 377C 80002B7C 00AB082B */  sltu       $at, $a1, $t3
/* 3780 80002B80 1020000F */  beqz       $at, .L80002BC0
/* 3784 80002B84 00000000 */   nop
/* 3788 80002B88 00804025 */  or         $t0, $a0, $zero
/* 378C 80002B8C 00854821 */  addu       $t1, $a0, $a1
/* 3790 80002B90 0109082B */  sltu       $at, $t0, $t1
/* 3794 80002B94 10200008 */  beqz       $at, .L80002BB8
/* 3798 80002B98 00000000 */   nop
/* 379C 80002B9C 310A000F */  andi       $t2, $t0, 0xF
/* 37A0 80002BA0 2529FFF0 */  addiu      $t1, $t1, -0x10
/* 37A4 80002BA4 010A4023 */  subu       $t0, $t0, $t2
.L80002BA8:
/* 37A8 80002BA8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
/* 37AC 80002BAC 0109082B */  sltu       $at, $t0, $t1
/* 37B0 80002BB0 1420FFFD */  bnez       $at, .L80002BA8
/* 37B4 80002BB4 25080010 */   addiu     $t0, $t0, 0x10
.L80002BB8:
/* 37B8 80002BB8 03E00008 */  jr         $ra
/* 37BC 80002BBC 00000000 */   nop
.L80002BC0:
/* 37C0 80002BC0 3C088000 */  lui        $t0, 0x8000
/* 37C4 80002BC4 010B4821 */  addu       $t1, $t0, $t3
/* 37C8 80002BC8 2529FFF0 */  addiu      $t1, $t1, -0x10
.L80002BCC:
/* 37CC 80002BCC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* 37D0 80002BD0 0109082B */  sltu       $at, $t0, $t1
/* 37D4 80002BD4 1420FFFD */  bnez       $at, .L80002BCC
/* 37D8 80002BD8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* 37DC 80002BDC 03E00008 */  jr         $ra
/* 37E0 80002BE0 00000000 */   nop
/* 37E4 80002BE4 00000000 */  nop
/* 37E8 80002BE8 00000000 */  nop
/* 37EC 80002BEC 00000000 */  nop
endlabel osWritebackDCache
.size osWritebackDCache, . - osWritebackDCache
