.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel bzero
/* F3F370 80263B40 28A1000C */  slti       $at, $a1, 0xC
/* F3F374 80263B44 1420001D */  bnez       $at, .L80263BBC
/* F3F378 80263B48 00041823 */   negu      $v1, $a0
/* F3F37C 80263B4C 30630003 */  andi       $v1, $v1, 0x3
/* F3F380 80263B50 10600003 */  beqz       $v1, .L80263B60
/* F3F384 80263B54 00A32823 */   subu      $a1, $a1, $v1
/* F3F388 80263B58 A8800000 */  swl        $zero, 0x0($a0)
/* F3F38C 80263B5C 00832021 */  addu       $a0, $a0, $v1
.L80263B60:
/* F3F390 80263B60 2401FFE0 */  addiu      $at, $zero, -0x20
/* F3F394 80263B64 00A13824 */  and        $a3, $a1, $at
/* F3F398 80263B68 10E0000C */  beqz       $a3, .L80263B9C
/* F3F39C 80263B6C 00A72823 */   subu      $a1, $a1, $a3
/* F3F3A0 80263B70 00E43821 */  addu       $a3, $a3, $a0
.L80263B74:
/* F3F3A4 80263B74 24840020 */  addiu      $a0, $a0, 0x20
/* F3F3A8 80263B78 AC80FFE0 */  sw         $zero, -0x20($a0)
/* F3F3AC 80263B7C AC80FFE4 */  sw         $zero, -0x1C($a0)
/* F3F3B0 80263B80 AC80FFE8 */  sw         $zero, -0x18($a0)
/* F3F3B4 80263B84 AC80FFEC */  sw         $zero, -0x14($a0)
/* F3F3B8 80263B88 AC80FFF0 */  sw         $zero, -0x10($a0)
/* F3F3BC 80263B8C AC80FFF4 */  sw         $zero, -0xC($a0)
/* F3F3C0 80263B90 AC80FFF8 */  sw         $zero, -0x8($a0)
/* F3F3C4 80263B94 1487FFF7 */  bne        $a0, $a3, .L80263B74
/* F3F3C8 80263B98 AC80FFFC */   sw        $zero, -0x4($a0)
.L80263B9C:
/* F3F3CC 80263B9C 2401FFFC */  addiu      $at, $zero, -0x4
/* F3F3D0 80263BA0 00A13824 */  and        $a3, $a1, $at
/* F3F3D4 80263BA4 10E00005 */  beqz       $a3, .L80263BBC
/* F3F3D8 80263BA8 00A72823 */   subu      $a1, $a1, $a3
/* F3F3DC 80263BAC 00E43821 */  addu       $a3, $a3, $a0
.L80263BB0:
/* F3F3E0 80263BB0 24840004 */  addiu      $a0, $a0, 0x4
/* F3F3E4 80263BB4 1487FFFE */  bne        $a0, $a3, .L80263BB0
/* F3F3E8 80263BB8 AC80FFFC */   sw        $zero, -0x4($a0)
.L80263BBC:
/* F3F3EC 80263BBC 18A00005 */  blez       $a1, .L80263BD4
/* F3F3F0 80263BC0 00000000 */   nop
/* F3F3F4 80263BC4 00A42821 */  addu       $a1, $a1, $a0
.L80263BC8:
/* F3F3F8 80263BC8 24840001 */  addiu      $a0, $a0, 0x1
/* F3F3FC 80263BCC 1485FFFE */  bne        $a0, $a1, .L80263BC8
/* F3F400 80263BD0 A080FFFF */   sb        $zero, -0x1($a0)
.L80263BD4:
/* F3F404 80263BD4 03E00008 */  jr         $ra
/* F3F408 80263BD8 00000000 */   nop
/* F3F40C 80263BDC 00000000 */  nop
endlabel bzero
.size bzero, . - bzero
