.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osWritebackDCache
/* F40320 80264AF0 18A00011 */  blez       $a1, .L80264B38
/* F40324 80264AF4 00000000 */   nop
/* F40328 80264AF8 240B2000 */  addiu      $t3, $zero, 0x2000
/* F4032C 80264AFC 00AB082B */  sltu       $at, $a1, $t3
/* F40330 80264B00 1020000F */  beqz       $at, .L80264B40
/* F40334 80264B04 00000000 */   nop
/* F40338 80264B08 00804025 */  or         $t0, $a0, $zero
/* F4033C 80264B0C 00854821 */  addu       $t1, $a0, $a1
/* F40340 80264B10 0109082B */  sltu       $at, $t0, $t1
/* F40344 80264B14 10200008 */  beqz       $at, .L80264B38
/* F40348 80264B18 00000000 */   nop
/* F4034C 80264B1C 310A000F */  andi       $t2, $t0, 0xF
/* F40350 80264B20 2529FFF0 */  addiu      $t1, $t1, -0x10
/* F40354 80264B24 010A4023 */  subu       $t0, $t0, $t2
.L80264B28:
/* F40358 80264B28 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
/* F4035C 80264B2C 0109082B */  sltu       $at, $t0, $t1
/* F40360 80264B30 1420FFFD */  bnez       $at, .L80264B28
/* F40364 80264B34 25080010 */   addiu     $t0, $t0, 0x10
.L80264B38:
/* F40368 80264B38 03E00008 */  jr         $ra
/* F4036C 80264B3C 00000000 */   nop
.L80264B40:
/* F40370 80264B40 3C088000 */  lui        $t0, 0x8000
/* F40374 80264B44 010B4821 */  addu       $t1, $t0, $t3
/* F40378 80264B48 2529FFF0 */  addiu      $t1, $t1, -0x10
.L80264B4C:
/* F4037C 80264B4C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* F40380 80264B50 0109082B */  sltu       $at, $t0, $t1
/* F40384 80264B54 1420FFFD */  bnez       $at, .L80264B4C
/* F40388 80264B58 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* F4038C 80264B5C 03E00008 */  jr         $ra
/* F40390 80264B60 00000000 */   nop
/* F40394 80264B64 00000000 */  nop
/* F40398 80264B68 00000000 */  nop
/* F4039C 80264B6C 00000000 */  nop
endlabel osWritebackDCache
.size osWritebackDCache, . - osWritebackDCache
