.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osWriteBackDCacheAll
/* F3F410 80263BE0 3C088000 */  lui        $t0, 0x8000
/* F3F414 80263BE4 240A2000 */  addiu      $t2, $zero, 0x2000
/* F3F418 80263BE8 010A4821 */  addu       $t1, $t0, $t2
/* F3F41C 80263BEC 2529FFF0 */  addiu      $t1, $t1, -0x10
.L80263BF0:
/* F3F420 80263BF0 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* F3F424 80263BF4 0109082B */  sltu       $at, $t0, $t1
/* F3F428 80263BF8 1420FFFD */  bnez       $at, .L80263BF0
/* F3F42C 80263BFC 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* F3F430 80263C00 03E00008 */  jr         $ra
/* F3F434 80263C04 00000000 */   nop
/* F3F438 80263C08 00000000 */  nop
/* F3F43C 80263C0C 00000000 */  nop
endlabel osWriteBackDCacheAll
.size osWriteBackDCacheAll, . - osWriteBackDCacheAll
