.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel bcopy
/* F47940 8026C110 10C0001A */  beqz       $a2, .L8026C17C
/* F47944 8026C114 00A03825 */   or        $a3, $a1, $zero
/* F47948 8026C118 10850018 */  beq        $a0, $a1, .L8026C17C
/* F4794C 8026C11C 00A4082A */   slt       $at, $a1, $a0
/* F47950 8026C120 54200008 */  bnel       $at, $zero, .L8026C144
/* F47954 8026C124 28C10010 */   slti      $at, $a2, 0x10
/* F47958 8026C128 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
/* F4795C 8026C12C 00A2082A */  slt        $at, $a1, $v0
/* F47960 8026C130 50200004 */  beql       $at, $zero, .L8026C144
/* F47964 8026C134 28C10010 */   slti      $at, $a2, 0x10
/* F47968 8026C138 1000005B */  b          .L8026C2A8
/* F4796C 8026C13C 28C10010 */   slti      $at, $a2, 0x10
/* F47970 8026C140 28C10010 */  slti       $at, $a2, 0x10
.L8026C144:
/* F47974 8026C144 14200005 */  bnez       $at, .L8026C15C
/* F47978 8026C148 00000000 */   nop
/* F4797C 8026C14C 30820003 */  andi       $v0, $a0, 0x3
/* F47980 8026C150 30A30003 */  andi       $v1, $a1, 0x3
/* F47984 8026C154 1043000B */  beq        $v0, $v1, .L8026C184
/* F47988 8026C158 00000000 */   nop
.L8026C15C:
/* F4798C 8026C15C 10C00007 */  beqz       $a2, .L8026C17C
/* F47990 8026C160 00000000 */   nop
/* F47994 8026C164 00861821 */  addu       $v1, $a0, $a2
.L8026C168:
/* F47998 8026C168 80820000 */  lb         $v0, 0x0($a0)
/* F4799C 8026C16C 24840001 */  addiu      $a0, $a0, 0x1
/* F479A0 8026C170 24A50001 */  addiu      $a1, $a1, 0x1
/* F479A4 8026C174 1483FFFC */  bne        $a0, $v1, .L8026C168
/* F479A8 8026C178 A0A2FFFF */   sb        $v0, -0x1($a1)
.L8026C17C:
/* F479AC 8026C17C 03E00008 */  jr         $ra
/* F479B0 8026C180 00E01025 */   or        $v0, $a3, $zero
.L8026C184:
/* F479B4 8026C184 10400018 */  beqz       $v0, .L8026C1E8
/* F479B8 8026C188 24010001 */   addiu     $at, $zero, 0x1
/* F479BC 8026C18C 1041000F */  beq        $v0, $at, .L8026C1CC
/* F479C0 8026C190 24010002 */   addiu     $at, $zero, 0x2
/* F479C4 8026C194 50410008 */  beql       $v0, $at, .L8026C1B8
/* F479C8 8026C198 84820000 */   lh        $v0, 0x0($a0)
/* F479CC 8026C19C 80820000 */  lb         $v0, 0x0($a0)
/* F479D0 8026C1A0 24840001 */  addiu      $a0, $a0, 0x1
/* F479D4 8026C1A4 24A50001 */  addiu      $a1, $a1, 0x1
/* F479D8 8026C1A8 24C6FFFF */  addiu      $a2, $a2, -0x1
/* F479DC 8026C1AC 1000000E */  b          .L8026C1E8
/* F479E0 8026C1B0 A0A2FFFF */   sb        $v0, -0x1($a1)
/* F479E4 8026C1B4 84820000 */  lh         $v0, 0x0($a0)
.L8026C1B8:
/* F479E8 8026C1B8 24840002 */  addiu      $a0, $a0, 0x2
/* F479EC 8026C1BC 24A50002 */  addiu      $a1, $a1, 0x2
/* F479F0 8026C1C0 24C6FFFE */  addiu      $a2, $a2, -0x2
/* F479F4 8026C1C4 10000008 */  b          .L8026C1E8
/* F479F8 8026C1C8 A4A2FFFE */   sh        $v0, -0x2($a1)
.L8026C1CC:
/* F479FC 8026C1CC 80820000 */  lb         $v0, 0x0($a0)
/* F47A00 8026C1D0 84830001 */  lh         $v1, 0x1($a0)
/* F47A04 8026C1D4 24840003 */  addiu      $a0, $a0, 0x3
/* F47A08 8026C1D8 24A50003 */  addiu      $a1, $a1, 0x3
/* F47A0C 8026C1DC 24C6FFFD */  addiu      $a2, $a2, -0x3
/* F47A10 8026C1E0 A0A2FFFD */  sb         $v0, -0x3($a1)
/* F47A14 8026C1E4 A4A3FFFE */  sh         $v1, -0x2($a1)
.L8026C1E8:
/* F47A18 8026C1E8 28C10020 */  slti       $at, $a2, 0x20
/* F47A1C 8026C1EC 54200016 */  bnel       $at, $zero, .L8026C248
/* F47A20 8026C1F0 28C10010 */   slti      $at, $a2, 0x10
/* F47A24 8026C1F4 8C820000 */  lw         $v0, 0x0($a0)
/* F47A28 8026C1F8 8C830004 */  lw         $v1, 0x4($a0)
/* F47A2C 8026C1FC 8C880008 */  lw         $t0, 0x8($a0)
/* F47A30 8026C200 8C89000C */  lw         $t1, 0xC($a0)
/* F47A34 8026C204 8C8A0010 */  lw         $t2, 0x10($a0)
/* F47A38 8026C208 8C8B0014 */  lw         $t3, 0x14($a0)
/* F47A3C 8026C20C 8C8C0018 */  lw         $t4, 0x18($a0)
/* F47A40 8026C210 8C8D001C */  lw         $t5, 0x1C($a0)
/* F47A44 8026C214 24840020 */  addiu      $a0, $a0, 0x20
/* F47A48 8026C218 24A50020 */  addiu      $a1, $a1, 0x20
/* F47A4C 8026C21C 24C6FFE0 */  addiu      $a2, $a2, -0x20
/* F47A50 8026C220 ACA2FFE0 */  sw         $v0, -0x20($a1)
/* F47A54 8026C224 ACA3FFE4 */  sw         $v1, -0x1C($a1)
/* F47A58 8026C228 ACA8FFE8 */  sw         $t0, -0x18($a1)
/* F47A5C 8026C22C ACA9FFEC */  sw         $t1, -0x14($a1)
/* F47A60 8026C230 ACAAFFF0 */  sw         $t2, -0x10($a1)
/* F47A64 8026C234 ACABFFF4 */  sw         $t3, -0xC($a1)
/* F47A68 8026C238 ACACFFF8 */  sw         $t4, -0x8($a1)
/* F47A6C 8026C23C 1000FFEA */  b          .L8026C1E8
/* F47A70 8026C240 ACADFFFC */   sw        $t5, -0x4($a1)
.L8026C244:
/* F47A74 8026C244 28C10010 */  slti       $at, $a2, 0x10
.L8026C248:
/* F47A78 8026C248 5420000E */  bnel       $at, $zero, .L8026C284
/* F47A7C 8026C24C 28C10004 */   slti      $at, $a2, 0x4
/* F47A80 8026C250 8C820000 */  lw         $v0, 0x0($a0)
/* F47A84 8026C254 8C830004 */  lw         $v1, 0x4($a0)
/* F47A88 8026C258 8C880008 */  lw         $t0, 0x8($a0)
/* F47A8C 8026C25C 8C89000C */  lw         $t1, 0xC($a0)
/* F47A90 8026C260 24840010 */  addiu      $a0, $a0, 0x10
/* F47A94 8026C264 24A50010 */  addiu      $a1, $a1, 0x10
/* F47A98 8026C268 24C6FFF0 */  addiu      $a2, $a2, -0x10
/* F47A9C 8026C26C ACA2FFF0 */  sw         $v0, -0x10($a1)
/* F47AA0 8026C270 ACA3FFF4 */  sw         $v1, -0xC($a1)
/* F47AA4 8026C274 ACA8FFF8 */  sw         $t0, -0x8($a1)
/* F47AA8 8026C278 1000FFF2 */  b          .L8026C244
/* F47AAC 8026C27C ACA9FFFC */   sw        $t1, -0x4($a1)
.L8026C280:
/* F47AB0 8026C280 28C10004 */  slti       $at, $a2, 0x4
.L8026C284:
/* F47AB4 8026C284 1420FFB5 */  bnez       $at, .L8026C15C
/* F47AB8 8026C288 00000000 */   nop
/* F47ABC 8026C28C 8C820000 */  lw         $v0, 0x0($a0)
/* F47AC0 8026C290 24840004 */  addiu      $a0, $a0, 0x4
/* F47AC4 8026C294 24A50004 */  addiu      $a1, $a1, 0x4
/* F47AC8 8026C298 24C6FFFC */  addiu      $a2, $a2, -0x4
/* F47ACC 8026C29C 1000FFF8 */  b          .L8026C280
/* F47AD0 8026C2A0 ACA2FFFC */   sw        $v0, -0x4($a1)
/* F47AD4 8026C2A4 28C10010 */  slti       $at, $a2, 0x10
.L8026C2A8:
/* F47AD8 8026C2A8 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
/* F47ADC 8026C2AC 14200005 */  bnez       $at, .L8026C2C4
/* F47AE0 8026C2B0 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
/* F47AE4 8026C2B4 30820003 */  andi       $v0, $a0, 0x3
/* F47AE8 8026C2B8 30A30003 */  andi       $v1, $a1, 0x3
/* F47AEC 8026C2BC 1043000D */  beq        $v0, $v1, .L8026C2F4
/* F47AF0 8026C2C0 00000000 */   nop
.L8026C2C4:
/* F47AF4 8026C2C4 10C0FFAD */  beqz       $a2, .L8026C17C
/* F47AF8 8026C2C8 00000000 */   nop
/* F47AFC 8026C2CC 2484FFFF */  addiu      $a0, $a0, -0x1
/* F47B00 8026C2D0 24A5FFFF */  addiu      $a1, $a1, -0x1
/* F47B04 8026C2D4 00861823 */  subu       $v1, $a0, $a2
.L8026C2D8:
/* F47B08 8026C2D8 80820000 */  lb         $v0, 0x0($a0)
/* F47B0C 8026C2DC 2484FFFF */  addiu      $a0, $a0, -0x1
/* F47B10 8026C2E0 24A5FFFF */  addiu      $a1, $a1, -0x1
/* F47B14 8026C2E4 1483FFFC */  bne        $a0, $v1, .L8026C2D8
/* F47B18 8026C2E8 A0A20001 */   sb        $v0, 0x1($a1)
/* F47B1C 8026C2EC 03E00008 */  jr         $ra
/* F47B20 8026C2F0 00E01025 */   or        $v0, $a3, $zero
.L8026C2F4:
/* F47B24 8026C2F4 10400018 */  beqz       $v0, .L8026C358
/* F47B28 8026C2F8 24010003 */   addiu     $at, $zero, 0x3
/* F47B2C 8026C2FC 1041000F */  beq        $v0, $at, .L8026C33C
/* F47B30 8026C300 24010002 */   addiu     $at, $zero, 0x2
/* F47B34 8026C304 50410008 */  beql       $v0, $at, .L8026C328
/* F47B38 8026C308 8482FFFE */   lh        $v0, -0x2($a0)
/* F47B3C 8026C30C 8082FFFF */  lb         $v0, -0x1($a0)
/* F47B40 8026C310 2484FFFF */  addiu      $a0, $a0, -0x1
/* F47B44 8026C314 24A5FFFF */  addiu      $a1, $a1, -0x1
/* F47B48 8026C318 24C6FFFF */  addiu      $a2, $a2, -0x1
/* F47B4C 8026C31C 1000000E */  b          .L8026C358
/* F47B50 8026C320 A0A20000 */   sb        $v0, 0x0($a1)
/* F47B54 8026C324 8482FFFE */  lh         $v0, -0x2($a0)
.L8026C328:
/* F47B58 8026C328 2484FFFE */  addiu      $a0, $a0, -0x2
/* F47B5C 8026C32C 24A5FFFE */  addiu      $a1, $a1, -0x2
/* F47B60 8026C330 24C6FFFE */  addiu      $a2, $a2, -0x2
/* F47B64 8026C334 10000008 */  b          .L8026C358
/* F47B68 8026C338 A4A20000 */   sh        $v0, 0x0($a1)
.L8026C33C:
/* F47B6C 8026C33C 8082FFFF */  lb         $v0, -0x1($a0)
/* F47B70 8026C340 8483FFFD */  lh         $v1, -0x3($a0)
/* F47B74 8026C344 2484FFFD */  addiu      $a0, $a0, -0x3
/* F47B78 8026C348 24A5FFFD */  addiu      $a1, $a1, -0x3
/* F47B7C 8026C34C 24C6FFFD */  addiu      $a2, $a2, -0x3
/* F47B80 8026C350 A0A20002 */  sb         $v0, 0x2($a1)
/* F47B84 8026C354 A4A30000 */  sh         $v1, 0x0($a1)
.L8026C358:
/* F47B88 8026C358 28C10020 */  slti       $at, $a2, 0x20
/* F47B8C 8026C35C 54200016 */  bnel       $at, $zero, .L8026C3B8
/* F47B90 8026C360 28C10010 */   slti      $at, $a2, 0x10
/* F47B94 8026C364 8C82FFFC */  lw         $v0, -0x4($a0)
/* F47B98 8026C368 8C83FFF8 */  lw         $v1, -0x8($a0)
/* F47B9C 8026C36C 8C88FFF4 */  lw         $t0, -0xC($a0)
/* F47BA0 8026C370 8C89FFF0 */  lw         $t1, -0x10($a0)
/* F47BA4 8026C374 8C8AFFEC */  lw         $t2, -0x14($a0)
/* F47BA8 8026C378 8C8BFFE8 */  lw         $t3, -0x18($a0)
/* F47BAC 8026C37C 8C8CFFE4 */  lw         $t4, -0x1C($a0)
/* F47BB0 8026C380 8C8DFFE0 */  lw         $t5, -0x20($a0)
/* F47BB4 8026C384 2484FFE0 */  addiu      $a0, $a0, -0x20
/* F47BB8 8026C388 24A5FFE0 */  addiu      $a1, $a1, -0x20
/* F47BBC 8026C38C 24C6FFE0 */  addiu      $a2, $a2, -0x20
/* F47BC0 8026C390 ACA2001C */  sw         $v0, 0x1C($a1)
/* F47BC4 8026C394 ACA30018 */  sw         $v1, 0x18($a1)
/* F47BC8 8026C398 ACA80014 */  sw         $t0, 0x14($a1)
/* F47BCC 8026C39C ACA90010 */  sw         $t1, 0x10($a1)
/* F47BD0 8026C3A0 ACAA000C */  sw         $t2, 0xC($a1)
/* F47BD4 8026C3A4 ACAB0008 */  sw         $t3, 0x8($a1)
/* F47BD8 8026C3A8 ACAC0004 */  sw         $t4, 0x4($a1)
/* F47BDC 8026C3AC 1000FFEA */  b          .L8026C358
/* F47BE0 8026C3B0 ACAD0000 */   sw        $t5, 0x0($a1)
.L8026C3B4:
/* F47BE4 8026C3B4 28C10010 */  slti       $at, $a2, 0x10
.L8026C3B8:
/* F47BE8 8026C3B8 5420000E */  bnel       $at, $zero, .L8026C3F4
/* F47BEC 8026C3BC 28C10004 */   slti      $at, $a2, 0x4
/* F47BF0 8026C3C0 8C82FFFC */  lw         $v0, -0x4($a0)
/* F47BF4 8026C3C4 8C83FFF8 */  lw         $v1, -0x8($a0)
/* F47BF8 8026C3C8 8C88FFF4 */  lw         $t0, -0xC($a0)
/* F47BFC 8026C3CC 8C89FFF0 */  lw         $t1, -0x10($a0)
/* F47C00 8026C3D0 2484FFF0 */  addiu      $a0, $a0, -0x10
/* F47C04 8026C3D4 24A5FFF0 */  addiu      $a1, $a1, -0x10
/* F47C08 8026C3D8 24C6FFF0 */  addiu      $a2, $a2, -0x10
/* F47C0C 8026C3DC ACA2000C */  sw         $v0, 0xC($a1)
/* F47C10 8026C3E0 ACA30008 */  sw         $v1, 0x8($a1)
/* F47C14 8026C3E4 ACA80004 */  sw         $t0, 0x4($a1)
/* F47C18 8026C3E8 1000FFF2 */  b          .L8026C3B4
/* F47C1C 8026C3EC ACA90000 */   sw        $t1, 0x0($a1)
.L8026C3F0:
/* F47C20 8026C3F0 28C10004 */  slti       $at, $a2, 0x4
.L8026C3F4:
/* F47C24 8026C3F4 1420FFB3 */  bnez       $at, .L8026C2C4
/* F47C28 8026C3F8 00000000 */   nop
/* F47C2C 8026C3FC 8C82FFFC */  lw         $v0, -0x4($a0)
/* F47C30 8026C400 2484FFFC */  addiu      $a0, $a0, -0x4
/* F47C34 8026C404 24A5FFFC */  addiu      $a1, $a1, -0x4
/* F47C38 8026C408 24C6FFFC */  addiu      $a2, $a2, -0x4
/* F47C3C 8026C40C 1000FFF8 */  b          .L8026C3F0
/* F47C40 8026C410 ACA20000 */   sw        $v0, 0x0($a1)
/* F47C44 8026C414 00000000 */  nop
/* F47C48 8026C418 00000000 */  nop
/* F47C4C 8026C41C 00000000 */  nop
endlabel bcopy
.size bcopy, . - bcopy
