.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osGetCount
/* F48630 8026CE00 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
/* F48634 8026CE04 03E00008 */  jr         $ra
/* F48638 8026CE08 00000000 */   nop
/* F4863C 8026CE0C 00000000 */  nop
endlabel osGetCount
.size osGetCount, . - osGetCount
