.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osGetSR
/* F45A50 8026A220 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
/* F45A54 8026A224 03E00008 */  jr         $ra
/* F45A58 8026A228 00000000 */   nop
/* F45A5C 8026A22C 00000000 */  nop
endlabel __osGetSR
.size __osGetSR, . - __osGetSR
