.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osInvalDCache
/* F403A0 80264B70 18A0001F */  blez       $a1, .L80264BF0
/* F403A4 80264B74 00000000 */   nop
/* F403A8 80264B78 240B2000 */  addiu      $t3, $zero, 0x2000
/* F403AC 80264B7C 00AB082B */  sltu       $at, $a1, $t3
/* F403B0 80264B80 1020001D */  beqz       $at, .L80264BF8
/* F403B4 80264B84 00000000 */   nop
/* F403B8 80264B88 00804025 */  or         $t0, $a0, $zero
/* F403BC 80264B8C 00854821 */  addu       $t1, $a0, $a1
/* F403C0 80264B90 0109082B */  sltu       $at, $t0, $t1
/* F403C4 80264B94 10200016 */  beqz       $at, .L80264BF0
/* F403C8 80264B98 00000000 */   nop
/* F403CC 80264B9C 310A000F */  andi       $t2, $t0, 0xF
/* F403D0 80264BA0 11400007 */  beqz       $t2, .L80264BC0
/* F403D4 80264BA4 2529FFF0 */   addiu     $t1, $t1, -0x10
/* F403D8 80264BA8 010A4023 */  subu       $t0, $t0, $t2
/* F403DC 80264BAC BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
/* F403E0 80264BB0 0109082B */  sltu       $at, $t0, $t1
/* F403E4 80264BB4 1020000E */  beqz       $at, .L80264BF0
/* F403E8 80264BB8 00000000 */   nop
/* F403EC 80264BBC 25080010 */  addiu      $t0, $t0, 0x10
.L80264BC0:
/* F403F0 80264BC0 312A000F */  andi       $t2, $t1, 0xF
/* F403F4 80264BC4 11400006 */  beqz       $t2, .L80264BE0
/* F403F8 80264BC8 00000000 */   nop
/* F403FC 80264BCC 012A4823 */  subu       $t1, $t1, $t2
/* F40400 80264BD0 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
/* F40404 80264BD4 0128082B */  sltu       $at, $t1, $t0
/* F40408 80264BD8 14200005 */  bnez       $at, .L80264BF0
/* F4040C 80264BDC 00000000 */   nop
.L80264BE0:
/* F40410 80264BE0 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
/* F40414 80264BE4 0109082B */  sltu       $at, $t0, $t1
/* F40418 80264BE8 1420FFFD */  bnez       $at, .L80264BE0
/* F4041C 80264BEC 25080010 */   addiu     $t0, $t0, 0x10
.L80264BF0:
/* F40420 80264BF0 03E00008 */  jr         $ra
/* F40424 80264BF4 00000000 */   nop
.L80264BF8:
/* F40428 80264BF8 3C088000 */  lui        $t0, 0x8000
/* F4042C 80264BFC 010B4821 */  addu       $t1, $t0, $t3
/* F40430 80264C00 2529FFF0 */  addiu      $t1, $t1, -0x10
.L80264C04:
/* F40434 80264C04 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* F40438 80264C08 0109082B */  sltu       $at, $t0, $t1
/* F4043C 80264C0C 1420FFFD */  bnez       $at, .L80264C04
/* F40440 80264C10 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* F40444 80264C14 03E00008 */  jr         $ra
/* F40448 80264C18 00000000 */   nop
/* F4044C 80264C1C 00000000 */  nop
endlabel osInvalDCache
.size osInvalDCache, . - osInvalDCache
