.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osInvalICache
/* F43CF0 802684C0 18A00011 */  blez       $a1, .L80268508
/* F43CF4 802684C4 00000000 */   nop
/* F43CF8 802684C8 240B4000 */  addiu      $t3, $zero, 0x4000
/* F43CFC 802684CC 00AB082B */  sltu       $at, $a1, $t3
/* F43D00 802684D0 1020000F */  beqz       $at, .L80268510
/* F43D04 802684D4 00000000 */   nop
/* F43D08 802684D8 00804025 */  or         $t0, $a0, $zero
/* F43D0C 802684DC 00854821 */  addu       $t1, $a0, $a1
/* F43D10 802684E0 0109082B */  sltu       $at, $t0, $t1
/* F43D14 802684E4 10200008 */  beqz       $at, .L80268508
/* F43D18 802684E8 00000000 */   nop
/* F43D1C 802684EC 310A001F */  andi       $t2, $t0, 0x1F
/* F43D20 802684F0 2529FFE0 */  addiu      $t1, $t1, -0x20
/* F43D24 802684F4 010A4023 */  subu       $t0, $t0, $t2
.L802684F8:
/* F43D28 802684F8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
/* F43D2C 802684FC 0109082B */  sltu       $at, $t0, $t1
/* F43D30 80268500 1420FFFD */  bnez       $at, .L802684F8
/* F43D34 80268504 25080020 */   addiu     $t0, $t0, 0x20
.L80268508:
/* F43D38 80268508 03E00008 */  jr         $ra
/* F43D3C 8026850C 00000000 */   nop
.L80268510:
/* F43D40 80268510 3C088000 */  lui        $t0, 0x8000
/* F43D44 80268514 010B4821 */  addu       $t1, $t0, $t3
/* F43D48 80268518 2529FFE0 */  addiu      $t1, $t1, -0x20
.L8026851C:
/* F43D4C 8026851C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
/* F43D50 80268520 0109082B */  sltu       $at, $t0, $t1
/* F43D54 80268524 1420FFFD */  bnez       $at, .L8026851C
/* F43D58 80268528 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
/* F43D5C 8026852C 03E00008 */  jr         $ra
/* F43D60 80268530 00000000 */   nop
/* F43D64 80268534 00000000 */  nop
/* F43D68 80268538 00000000 */  nop
/* F43D6C 8026853C 00000000 */  nop
endlabel osInvalICache
.size osInvalICache, . - osInvalICache
