.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osProbeTLB
/* F46C50 8026B420 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* F46C54 8026B424 310900FF */  andi       $t1, $t0, 0xFF
/* F46C58 8026B428 2401E000 */  addiu      $at, $zero, -0x2000
/* F46C5C 8026B42C 00815024 */  and        $t2, $a0, $at
/* F46C60 8026B430 012A4825 */  or         $t1, $t1, $t2
/* F46C64 8026B434 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* F46C68 8026B438 00000000 */  nop
/* F46C6C 8026B43C 00000000 */  nop
/* F46C70 8026B440 00000000 */  nop
/* F46C74 8026B444 42000008 */  tlbp /* handwritten instruction */
/* F46C78 8026B448 00000000 */  nop
/* F46C7C 8026B44C 00000000 */  nop
/* F46C80 8026B450 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
/* F46C84 8026B454 3C018000 */  lui        $at, (0x80000000 >> 16)
/* F46C88 8026B458 01615824 */  and        $t3, $t3, $at
/* F46C8C 8026B45C 1560001A */  bnez       $t3, .L8026B4C8
/* F46C90 8026B460 00000000 */   nop
/* F46C94 8026B464 42000001 */  tlbr /* handwritten instruction */
/* F46C98 8026B468 00000000 */  nop
/* F46C9C 8026B46C 00000000 */  nop
/* F46CA0 8026B470 00000000 */  nop
/* F46CA4 8026B474 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
/* F46CA8 8026B478 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
/* F46CAC 8026B47C 000B5842 */  srl        $t3, $t3, 1
/* F46CB0 8026B480 01646024 */  and        $t4, $t3, $a0
/* F46CB4 8026B484 15800004 */  bnez       $t4, .L8026B498
/* F46CB8 8026B488 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
/* F46CBC 8026B48C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
/* F46CC0 8026B490 10000002 */  b          .L8026B49C
/* F46CC4 8026B494 00000000 */   nop
.L8026B498:
/* F46CC8 8026B498 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
.L8026B49C:
/* F46CCC 8026B49C 304D0002 */  andi       $t5, $v0, 0x2
/* F46CD0 8026B4A0 11A00009 */  beqz       $t5, .L8026B4C8
/* F46CD4 8026B4A4 00000000 */   nop
/* F46CD8 8026B4A8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
/* F46CDC 8026B4AC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
/* F46CE0 8026B4B0 00411024 */  and        $v0, $v0, $at
/* F46CE4 8026B4B4 00021180 */  sll        $v0, $v0, 6
/* F46CE8 8026B4B8 008B6824 */  and        $t5, $a0, $t3
/* F46CEC 8026B4BC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
/* F46CF0 8026B4C0 10000002 */  b          .L8026B4CC
/* F46CF4 8026B4C4 00000000 */   nop
.L8026B4C8:
/* F46CF8 8026B4C8 2402FFFF */  addiu      $v0, $zero, -0x1
.L8026B4CC:
/* F46CFC 8026B4CC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* F46D00 8026B4D0 03E00008 */  jr         $ra
/* F46D04 8026B4D4 00000000 */   nop
/* F46D08 8026B4D8 00000000 */  nop
/* F46D0C 8026B4DC 00000000 */  nop
endlabel __osProbeTLB
.size __osProbeTLB, . - __osProbeTLB
