.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osSetCompare
/* F482A0 8026CA70 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
/* F482A4 8026CA74 03E00008 */  jr         $ra
/* F482A8 8026CA78 00000000 */   nop
/* F482AC 8026CA7C 00000000 */  nop
endlabel __osSetCompare
.size __osSetCompare, . - __osSetCompare
