.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel __osSetFpcCsr
/* F45A60 8026A230 4442F800 */  cfc1       $v0, $31
/* F45A64 8026A234 44C4F800 */  ctc1       $a0, $31
/* F45A68 8026A238 03E00008 */  jr         $ra
/* F45A6C 8026A23C 00000000 */   nop
endlabel __osSetFpcCsr
.size __osSetFpcCsr, . - __osSetFpcCsr
