.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osSetSR
/* F45A40 8026A210 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
/* F45A44 8026A214 00000000 */  nop
/* F45A48 8026A218 03E00008 */  jr         $ra
/* F45A4C 8026A21C 00000000 */   nop
endlabel __osSetSR
.size __osSetSR, . - __osSetSR
